name: Snake Game Generator

on:
  push:
    branches:
      - main
      - master

jobs:
  generate-snake:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Snake
        uses: platane/snk@v2
        with:
          github_user: RihabGouriani
          svg_out_path: svg/output.svg
          png_out_path: png/output.png
          color_snake: "#00ff00"
          color_food: "#ff0000"
          color_background: "#000000"
          # Add other options as needed
